# Generated by Django 4.1.5 on 2023-01-23 03:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=120)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('citizenship', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=120)),
                ('keywords', models.TextField()),
                ('desired_salary', models.CharField(max_length=20, null=True)),
                ('work_experience', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
